version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: car-rental-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: car-rental
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - car-rental

volumes:
  postgresql-data:

networks:
  car-rental:
    name: car-rental
    driver: bridge
